language: csharp
solution: BusTickets.WebAPI/BusTickets.WebAPI.sln
sudo: false
dist: trusty
mono: none
dotnet: 2.0.0
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1   
os:
  - linux
branches:
  only:
    - master
    - Development
script:
  - dotnet restore
  - dotnet build -c Release
  
